/*
** LEXGEN Lua Extension
**
** This module provides Lua bindings for the lexgen library,
** allowing runtime lexer generation from Lua scripts.
**
** Build: gcc -shared -fPIC -o lexgen_lua.so lexgen_lua.c lexgen.c -I/usr/include/lua5.3 -llua5.3
**        (adjust Lua version and paths as needed)
**
** Usage from Lua:
**   local lexgen = require("lexgen_lua")
**   local ctx = lexgen.new()
**   local state = ctx:parse_regex("\\d+", "NUMBER")
**   ctx:generate_code("output.c")
*/

#include "lexgen.h"
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include <stdlib.h>
#include <string.h>

#define LEXGEN_CTX_MT "LexGen.Context"
#define LEXGEN_STATE_MT "LexGen.State"
#define LEXGEN_SYM_MT "LexGen.Symbol"

/* Symbol wrapper for Lua */
struct lua_symbol {
    char *name;
    int index;
};

/* Context wrapper for Lua */
struct lua_lexgen_ctx {
    struct LexerContext ctx;
    int symbol_counter;
};

/*
** Helper: Check if userdata is a LexerContext
*/
static struct lua_lexgen_ctx *check_context(lua_State *L, int index) {
    return (struct lua_lexgen_ctx *)luaL_checkudata(L, index, LEXGEN_CTX_MT);
}

/*
** Helper: Create a new symbol
*/
static struct lua_symbol *create_lua_symbol(lua_State *L, const char *name, int index) {
    struct lua_symbol *sym = (struct lua_symbol *)lua_newuserdata(L, sizeof(struct lua_symbol));
    sym->name = strdup(name);
    sym->index = index;
    luaL_setmetatable(L, LEXGEN_SYM_MT);
    return sym;
}

/*
** lexgen.new() - Create a new lexer context
**
** Returns: context userdata
*/
static int l_lexgen_new(lua_State *L) {
    struct lua_lexgen_ctx *lctx = (struct lua_lexgen_ctx *)lua_newuserdata(L, sizeof(struct lua_lexgen_ctx));
    lexgen_init(&lctx->ctx, lexgen_get_default_classlist());
    lctx->symbol_counter = 0;
    
    luaL_setmetatable(L, LEXGEN_CTX_MT);
    return 1;
}

/*
** ctx:parse_regex(pattern, token_name [, mode [, next_mode [, action_code [, is_capturing]]]])
**
** Parse a regex pattern and create lexer states.
**
** Arguments:
**   pattern: regex pattern string
**   token_name: name of the token
**   mode: lexer mode name (default: "INITMODE")
**   next_mode: next mode to switch to (default: nil)
**   action_code: action code to execute (default: nil)
**   is_capturing: whether to capture (default: true)
**
** Returns: state userdata or nil on error
*/
static int l_ctx_parse_regex(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    const char *pattern = luaL_checkstring(L, 2);
    const char *token_name = luaL_checkstring(L, 3);
    const char *mode = luaL_optstring(L, 4, "INITMODE");
    const char *next_mode = lua_tostring(L, 5);  /* may be nil */
    const char *action_code = lua_tostring(L, 6);  /* may be nil */
    int is_capturing = lua_isboolean(L, 7) ? lua_toboolean(L, 7) : 1;
    
    /* Create a symbol */
    struct lua_symbol *sym = create_lua_symbol(L, token_name, ++lctx->symbol_counter);
    
    /* Parse the regex */
    struct LxState *state = lexgen_parse_regex(
        &lctx->ctx,
        pattern,
        mode,
        (struct symbol *)sym,
        next_mode,
        action_code,
        is_capturing
    );
    
    if (state) {
        /* Return the state as light userdata (for reference) */
        lua_pushlightuserdata(L, state);
        return 1;
    } else {
        lua_pushnil(L);
        lua_pushstring(L, "Failed to parse regex pattern");
        return 2;
    }
}

/*
** ctx:generate_code(filename)
**
** Generate C code for the lexer and write to file.
**
** Arguments:
**   filename: output file path
**
** Returns: true on success, nil + error message on failure
*/
static int l_ctx_generate_code(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    const char *filename = luaL_checkstring(L, 2);
    
    FILE *out = fopen(filename, "w");
    if (!out) {
        lua_pushnil(L);
        lua_pushfstring(L, "Cannot open file: %s", filename);
        return 2;
    }
    
    fprintf(out, "/* Auto-generated lexer code */\n");
    fprintf(out, "/* Generated by lexgen Lua extension */\n\n");
    fprintf(out, "#include <stdio.h>\n\n");
    
    int lineno = 5;
    Lexer_generate_class_list(&lctx->ctx, out, &lineno);
    
    fprintf(out, "\n/* Lexer state machine implementation */\n");
    lexgen_generate_code(&lctx->ctx, out, &lineno);
    
    fclose(out);
    
    lua_pushboolean(L, 1);
    return 1;
}

/*
** ctx:get_state_count()
**
** Get the number of states created.
**
** Returns: number of states
*/
static int l_ctx_get_state_count(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    lua_pushinteger(L, lctx->ctx.next_lxstate_id - 1);
    return 1;
}

/*
** ctx:get_mode_name()
**
** Get the name of the first mode.
**
** Returns: mode name or nil
*/
static int l_ctx_get_mode_name(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    if (lctx->ctx.first_mode && lctx->ctx.first_mode->name) {
        lua_pushstring(L, lctx->ctx.first_mode->name);
    } else {
        lua_pushstring(L, "INITMODE");
    }
    return 1;
}

/*
** ctx:set_debug_level(level)
**
** Set debug output level (0-2).
**
** Arguments:
**   level: debug level (0=off, 1=normal, 2=verbose)
**
** Returns: true
*/
static int l_ctx_set_debug_level(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    int level = luaL_checkinteger(L, 2);
    lctx->ctx.debug_level = level;
    lua_pushboolean(L, 1);
    return 1;
}

/*
** ctx:set_nesting_depth(depth)
**
** Set maximum nesting depth for lexer modes.
**
** Arguments:
**   depth: maximum nesting depth
**
** Returns: true
*/
static int l_ctx_set_nesting_depth(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    int depth = luaL_checkinteger(L, 2);
    lctx->ctx.nesting_depth = depth;
    lua_pushboolean(L, 1);
    return 1;
}

/*
** __gc metamethod for context
*/
static int l_ctx_gc(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    lexgen_cleanup(&lctx->ctx);
    return 0;
}

/*
** __tostring metamethod for context
*/
static int l_ctx_tostring(lua_State *L) {
    struct lua_lexgen_ctx *lctx = check_context(L, 1);
    lua_pushfstring(L, "LexGen.Context: %d states", lctx->ctx.next_lxstate_id - 1);
    return 1;
}

/*
** __gc metamethod for symbol
*/
static int l_sym_gc(lua_State *L) {
    struct lua_symbol *sym = (struct lua_symbol *)lua_touserdata(L, 1);
    if (sym && sym->name) {
        free(sym->name);
        sym->name = NULL;
    }
    return 0;
}

/*
** lexgen.utf8_char(codepoint)
**
** Convert Unicode codepoint to UTF-8 string.
**
** Arguments:
**   codepoint: Unicode codepoint (integer)
**
** Returns: UTF-8 string
*/
static int l_utf8_char(lua_State *L) {
    int codepoint = luaL_checkinteger(L, 1);
    char buf[8];
    int len = lxUtf8_str(codepoint, 0, buf);
    buf[len] = '\0';
    lua_pushlstring(L, buf, len);
    return 1;
}

/*
** lexgen.utf8_decode(str)
**
** Decode UTF-8 string to array of codepoints.
**
** Arguments:
**   str: UTF-8 string
**
** Returns: table of codepoints
*/
static int l_utf8_decode(lua_State *L) {
    const char *str = luaL_checkstring(L, 1);
    lua_newtable(L);
    
    int i = 1;
    while (*str) {
        int offset;
        int ch = lxUtf8_nextchar(str, &offset);
        lua_pushinteger(L, ch);
        lua_rawseti(L, -2, i++);
        str += offset;
    }
    
    return 1;
}

/*
** lexgen.version()
**
** Get library version information.
**
** Returns: version string
*/
static int l_version(lua_State *L) {
    lua_pushstring(L, "LEXGEN 1.0 - Lexer Generator Library (Lua Extension)");
    return 1;
}

/* Context methods */
static const luaL_Reg ctx_methods[] = {
    {"parse_regex", l_ctx_parse_regex},
    {"generate_code", l_ctx_generate_code},
    {"get_state_count", l_ctx_get_state_count},
    {"get_mode_name", l_ctx_get_mode_name},
    {"set_debug_level", l_ctx_set_debug_level},
    {"set_nesting_depth", l_ctx_set_nesting_depth},
    {"__gc", l_ctx_gc},
    {"__tostring", l_ctx_tostring},
    {NULL, NULL}
};

/* Module functions */
static const luaL_Reg lexgen_funcs[] = {
    {"new", l_lexgen_new},
    {"utf8_char", l_utf8_char},
    {"utf8_decode", l_utf8_decode},
    {"version", l_version},
    {NULL, NULL}
};

/*
** Module initialization
*/
int luaopen_lexgen_lua(lua_State *L) {
    /* Create context metatable */
    luaL_newmetatable(L, LEXGEN_CTX_MT);
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_setfuncs(L, ctx_methods, 0);
    lua_pop(L, 1);
    
    /* Create symbol metatable */
    luaL_newmetatable(L, LEXGEN_SYM_MT);
    lua_pushcfunction(L, l_sym_gc);
    lua_setfield(L, -2, "__gc");
    lua_pop(L, 1);
    
    /* Create module table */
    luaL_newlib(L, lexgen_funcs);
    
    /* Add constants */
    lua_pushinteger(L, LXCLASS_LETTER);
    lua_setfield(L, -2, "CLASS_LETTER");
    lua_pushinteger(L, LXCLASS_DIGIT);
    lua_setfield(L, -2, "CLASS_DIGIT");
    lua_pushinteger(L, LXCLASS_WORD);
    lua_setfield(L, -2, "CLASS_WORD");
    lua_pushinteger(L, LXCLASS_SPACE);
    lua_setfield(L, -2, "CLASS_SPACE");
    lua_pushinteger(L, LXCLASS_DOT);
    lua_setfield(L, -2, "CLASS_DOT");
    
    return 1;
}
